# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: spanner
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  project: <%= ENV.fetch("PROJECT_ID") { "" } %>
  instance: <%= ENV.fetch("SPANNER_INSTANCE") { "" } %>
  timeout: 5000

development:
  <<: *default
  emulator_host: <%= ENV.fetch("SPANNER_HOST") { "" } %>
  database: spanner_test_dev

production:
  <<: *default
  database: spanner_test
